In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle
import os



In [3]:
df = pd.read_csv("reviews.csv")
df.head()


,category,rating,label,text_
0,Home_and_Kitchen_5,5.0,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,CG,Very nice set. Good quality. We have had the s...


In [6]:
df.tail()

,category,rating,label,text_
40427,Clothing_Shoes_and_Jewelry_5,4.0,OR,I had read some reviews saying that this bra r...
40428,Clothing_Shoes_and_Jewelry_5,5.0,CG,I wasn't sure exactly what it would be. It is ...
40429,Clothing_Shoes_and_Jewelry_5,2.0,OR,"You can wear the hood by itself, wear it with ..."
40430,Clothing_Shoes_and_Jewelry_5,1.0,CG,I liked nothing about this dress. The only rea...
40431,Clothing_Shoes_and_Jewelry_5,5.0,OR,I work in the wedding industry and have to wor...


In [7]:
df.isnull().sum()


category    0
rating      0
label       0
text_       0
dtype: int64

In [21]:
df.shape

(40432, 4)

In [23]:
print("\nSummary:")
print(df.describe(include='all'))
print("\nNull Values:")
print(df.isnull().sum())



Summary:
              category        rating         label  \
count            40432  40432.000000  40432.000000   
unique              10           NaN           NaN   
top     Kindle_Store_5           NaN           NaN   
freq              4730           NaN           NaN   
mean               NaN      4.256579      0.500000   
std                NaN      1.144354      0.500006   
min                NaN      1.000000      0.000000   
25%                NaN      4.000000      0.000000   
50%                NaN      5.000000      0.500000   
75%                NaN      5.000000      1.000000   
max                NaN      5.000000      1.000000   

                                                    text_  
count                                               40432  
unique                                              40412  
top     My dog loves it and it has kept her occupied f...  
freq                                                    2  
mean                                     

In [9]:
df.columns


Index(['category', 'rating', 'label', 'text_'], dtype='object')

In [10]:
df['text_'] = df['text_'].fillna("")    
df['label'] = df['label'].fillna(0)      
df.isnull().sum()



category    0
rating      0
label       0
text_       0
dtype: int64

In [11]:
df['label'] = df['label'].map({'CG': 0, 'OR': 1})
df['label'].unique()


array([0, 1])

In [12]:
df['label'].value_counts()


label
0    20216
1    20216
Name: count, dtype: int64

In [13]:
texts = df['text_']
labels = df['label']


In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)


Training data: (32345,)
Testing data: (8087,)


In [15]:
vectorizer = TfidfVectorizer(stop_words='english')

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

X_train_vec.shape, X_test_vec.shape


((32345, 36673), (8087, 36673))

In [16]:
model = LogisticRegression()
model.fit(X_train_vec, y_train)

print("Model training completed!")


Model training completed!


In [17]:
y_pred = model.predict(X_test_vec)
y_pred[:10]


array([0, 0, 1, 0, 1, 1, 0, 1, 0, 1])

In [18]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.8645975021639669


In [19]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Confusion Matrix:
 [[3366  650]
 [ 445 3626]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.84      0.86      4016
           1       0.85      0.89      0.87      4071

    accuracy                           0.86      8087
   macro avg       0.87      0.86      0.86      8087
weighted avg       0.87      0.86      0.86      8087



In [20]:
os.makedirs("model", exist_ok=True)

with open("model/fake_review_model.pkl", "wb") as file:
    pickle.dump((vectorizer, model), file)

print("Model Saved Successfully!")


Model Saved Successfully!
